### ISSUE TITLE
Convert repo to public and make the master branch be the default branch

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/example-wordpress-composer#1]
@greg-1-anderson and @ataylorme, I made this empty repo so that I could start making issues under it and link to them in the readme. I hope to take this repo from private to public tomorrow.

- [x] Get CircleCI running and passing on this repo
- [x] Squash master branch? @greg-1-anderson, @ataylorme what do you think. I don't think we benefit from 100+ commits of CI debugging. I'd be fine squashing down to one for this initial release.
- [x] Merge Build Plugin PRs to add WordPress support simple WP support in [1.x](https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/67) and [master](https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/66)
- [x] Make repo public
- [x] Register with packagist
- [x] Update Build Plugin Tests to use this repo: https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/60
- [ ] Wait for https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/60 to be merged. 
- [x] Make the master branch be the default branch of the repo and delete `coming-soon` branch.

**Comment by stevector** [comment]
Merging https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/60 has proven more difficult than expected. Going to skip that step.

**Comment by greg-1-anderson** [comment]
It's merged now!
