### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by nelsonamaya82** [pantheon-systems/example-wordpress-composer#184]
I've been doing some tests with the `build:project:create` command using this `example-wordpress-composer` template. However I'm facing an issue on Bitbucket: After pushing some code to master and running my pipelines, when I get to the command:

`rsync -a web/wp/wp-content/mu-plugins/pantheon web/wp/wp-content/mu-plugins/pantheon.php web/wp-content/mu-plugins/`

I get this error:

`rsync: chgrp "/opt/atlassian/pipelines/agent/build/web/wp-content/mu-plugins/pantheon" failed: Operation not permitted (1)`

[Screenshot](https://cl.ly/6cb1e37eaf67)

I'm not sure if it's a bug or something I'm doing wrong.

BTW that command is [here](https://github.com/pantheon-systems/example-wordpress-composer/blob/5a7c8f34c9cbbde5466a5ecde84eae830ae962d1/scripts/composer/cleanup-composer#L7).

What is that command for? Is it required for this template to work with the Bitbucket Pipelines integration with Pantheon?

Thank you.

**Comment by ataylorme** [comment]
@nelsonamaya82 I've been testing some BitBucket items and they are having an outage.

It seems like it also might be a file permissions issue.

The rsync `-a` command tracks file permissions.

What happens if you change `rsync -a web/wp/wp-content/mu-plugins/* web/wp-content/mu-plugins/` to `rsync -r web/wp/wp-content/mu-plugins/* web/wp-content/mu-plugins/`?

**Comment by nelsonamaya82** [comment]
> What happens if you change `rsync -a web/wp/wp-content/mu-plugins/* web/wp-content/mu-plugins/` to `rsync -r web/wp/wp-content/mu-plugins/* web/wp-content/mu-plugins/`?

That definitely did the trick, thanks @ataylorme !!

**Comment by ataylorme** [comment]
Awesome! Want to submit a PR to this repo and https://github.com/pantheon-systems/example-drops-8-composer? It would be a 2 for 1 for [Hacktoberfest](https://hacktoberfest.digitalocean.com)

**Comment by nelsonamaya82** [comment]
Sure I'll do! I cannot find this command in https://github.com/pantheon-systems/example-drops-8-composer but will submit a PR to this repo.

**Comment by ataylorme** [comment]
> I cannot find this command in pantheon-systems/example-drops-8-composer

@nelsonamaya82 you are right, sorry about that. This is only needed for WordPress to ensure [the Pantheon `mu-plugin` in `pantheon-systems/wordpress/composer`](https://github.com/pantheon-systems/wordpress-composer/tree/master/wp-content/mu-plugins) is copied to the `mu-plugins` folder correctly.

**Comment by ataylorme** [comment]
Some of the CI steps are using `rsync -a` as well. See https://github.com/pantheon-systems/example-wordpress-composer/blob/master/.circleci/config.yml#L139

You could update those to `-r` in your pull request as well
