### ISSUE TITLE
Remove WordHat fork

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/example-wordpress-composer#2]
Currently composer.json references https://github.com/ataylorme/behat-wordpress-extension because there are some open PRs to the original that are necessary to get the extension working on Pantheon: https://github.com/paulgibbs/behat-wordpress-extension/pulls/ataylorme

Once those are closed we can remove 

```
    {           
      "type": "vcs",
      "url": "https://github.com/ataylorme/behat-wordpress-extension"
    }
```

**Comment by ataylorme** [comment]
Addressed in #13
