### ISSUE TITLE
Trigger Behat with Quicksilver

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/example-wordpress-composer#23]
Behat tests create/restore a backup. 

I've started the `circle-2-behat-quicksilver` branch to trigger Behat from Quicksilver and exclude it as part of standard builds.

The idea is to run faster tests, like code sniffing and unit tests, on CircleCI for each commit/PR. Once multiple PRs are merged and deployed to `test` on Pantheon the Quicksilver would trigger longer running tests on CircleCI, such as Behat.

Would love to get input from @greg-1-anderson and @stevector on this method.

**Comment by greg-1-anderson** [comment]
My experience with behat on the platform were not fruitful; there wasn't enough memory to run my tests.

I'll be interested to see if you get better results. Ultimately, it would be an improvement to run the build and test steps on the platform.

**Comment by ataylorme** [comment]
> My experience with behat on the platform were not fruitful; there wasn't enough memory to run my tests.

@greg-1-anderson the goal isn't to run Behat itself on Pantheon - that will still happen on CircleCI - but to simply trigger Behat from a Quicksilver hook when code is deployed to the test environment on Pantheon. The tests will run against the site on Pantheon but the Behat job will be triggered via API on Circle CI

**Comment by greg-1-anderson** [comment]
Ah, I see. That sounds like a good idea.

**Comment by stevector** [comment]
> Once multiple PRs are merged and deployed to test on Pantheon the Quicksilver would trigger longer running tests on CircleCI, such as Behat

Running behavioral tests only on the `test` environment seems too late in the deployment pipeline, IMO. Behat fails should indicate that an expected behavior of the site has regressed. I think most teams would want to know that ASAP, not at the last step before going live.

I agree that Behat tests can be slow. But they can just be run after all other build steps and tests have completed.

**Comment by ataylorme** [comment]
> I agree that Behat tests can be slow. But they can just be run after all other build steps and tests have completed.

That is what is happening in #22 at the moment. Code sniffing and unit testing run in parallel, then deployment to Pantheon, followed by Behat tests.

> Behat fails should indicate that an expected behavior of the site has regressed. I think most teams would want to know that ASAP, not at the last step before going live.

I agree with that. I think we can leave this as-is in the example. Perhaps we just just document the possibility. If teams get lots of tests they can split things up on their own later.
