### ISSUE TITLE
Use Docker

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/example-wordpress-composer#25]
The globals script contains the line Commands below this line would not be transferable to a docker container. But there are a couple of items being installed below that line that could be moved to Dockerfile:

* Terminus
* Terminus Secrets plugin
* prestissimo

@stevector any reason the Terminus build tools plugin isn't on this list?

**Comment by stevector** [comment]
Because we have logic to install alternate versions at run time:

```
composer create-project -n -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:$BUILD_TOOLS_VERSION
```

Though we could have stable installed in the Dockerfile and then checkout a specific branch if necessary at run time.

**Comment by stevector** [comment]
Greg is working on Dockerizing the Drupal example over in https://github.com/pantheon-systems/example-drops-8-composer/issues/103. Once that is done we should be able to copy changes back here.

**Comment by ataylorme** [comment]
Closing this out as `example-wordpress-composer` uses `quay.io/pantheon-public/build-tools-ci:6.x`
