### ISSUE TITLE
Move deploy to Pantheon logic to global

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/example-wordpress-composer#28]
[`deploy_to_pantheon.sh`](https://github.com/pantheon-systems/example-wordpress-composer/blob/a070ac3700399738c073614b39686c7e5a165203/.circleci/deploy-to-pantheon.sh#L26:L32) largely detects whether we should deploy to Pantheon or not. 

This logic should be moved to `set-up-globals.sh` and a `DEPLOY_TO_PANTHEON` variable created. We can then use `DEPLOY_TO_PANTHEON` to determine if the job should even run at all.

**Comment by greg-1-anderson** [comment]
The deploy_to_pantheon script largely duplicates behavior already available in the Terminus Build Tools plugin. I suggest we unify behavior between this repo and the drops-8 counterpart per https://github.com/pantheon-systems/example-drops-8-composer/issues/111.

set-up-globals.sh is called 00-set-environment there; this script is currently responsible for determining the environment name: https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.circleci/scripts/00-set-environment#L21

We still need to discuss and implement logic on when to run the full tests, though.

**Comment by ataylorme** [comment]
@greg-1-anderson thinking about using build number as the `TERMINUS_ENV` if a pull request is not open has issues. Each job is a new build and has it's own build number. So the Behat run will be looking for a multidev that was spun up using the job number from a different job.

**Comment by greg-1-anderson** [comment]
@ataylorme Good point. This worked well in Circle 1.x, but would be broken for cross-step multidev references in Circle 2.0.

In the current scripts in example-drops-8-composer, there is only one build step that references the multidev `TERMINUS_ENV`, so this is not broken at the moment. However, if we use this convention, we would have to be careful not to break it if adding more parallelism to builds.

I still believe that commits to the `master` branch should be tested; in this scenario, we need *some* identifier other than the pull request ID to use in generating the `TERMINUS_ENV`.

**Comment by ataylorme** [comment]
> I still believe that commits to the master branch should be tested; in this scenario, we need some identifier other than the pull request ID to use in generating the TERMINUS_ENV.

For `master` what about `ci-master`? It's less than 11 characters. We could then use `pr-` for pull requests and just not deploy anything that isn't a PR to Pantheon.

**Comment by greg-1-anderson** [comment]
`ci-master` would be problematic if overlapping tests ran on the master branch.
