### ISSUE TITLE
Auto-Creation of Multidev Envs is Problematic

### ISSUE THREAD

**Issue by cjyabraham** [pantheon-systems/example-wordpress-composer#77]
I've been testing this repo using [these instructions](https://pantheon.io/docs/guides/build-tools/new-pr/) to observe how multidev environments are spun up for branches.  I'm finding that following the instructions by editing through the web and immediately creating a PR does not, in fact, create a multidev environment as described.  It's only when you make a subsequent commit to that branch that a multidev env gets created.

The document also states that "As soon as you commit changes to a feature branch, CircleCI builds a new Multidev environment on Pantheon to preview the change."  This does not work unless you already have a PR open for that branch.

In the case when you want to make a single commit, then create a PR and merge, you will never get a multidev instance created.  If you want to force one to get created, you have to make an extra commit (which you may not need) after the PR is open.

I think it would be nice to have a multidev env created for a branch, whether or not there is a PR already open for that branch.  Is this possible?

**Comment by cjyabraham** [comment]
Hi @ataylorme , is this issue valid or was it by design that you only create Multidev instances for PRs?  Wouldn't you want them for all branches regardless of whether a PR is created?

**Comment by cjyabraham** [comment]
Ah, I'm seeing a lot of discussion regarding this [in this open issue](https://github.com/pantheon-systems/example-wordpress-composer/issues/40) but it's been a while since much has been said.  Are people happy now with the current configuration?

**Comment by ataylorme** [comment]
@cjyabraham I can't speak for others but I personally still prefer to only use multidevs when a pull request is present. There is a CircleCI option to only build pull requests, which I enable on my Terminus build tools created projects.

**Comment by cjyabraham** [comment]
@ataylorme I think the biggest pain point to that is that you have to make a commit after creating the PR in order to get the multidev env created, at least in my experience.  So sometimes I have to just create a useless commit to trigger this.  What do you do in this situation?

**Comment by ataylorme** [comment]
I have not experienced the need for an additional commit after PR creation when the only build PR option in CircleCI is used.

My workflow is to create/use a branch locally and push it to GitHub. When the work is ready for testing I create a PR. CircleCI then deploys the branch to a multidev, runs automated tests, etc. At that point, I can also get a code review. When everything looks good the PR is merged.

**Comment by cjyabraham** [comment]
Hi @ataylorme, I set the "only build PR" option and now the build gets triggered as soon as I create the PR and I don't need to make another commit.  This is great and solves that problem.  Thanks for your help.  I'll close this issue for now.
