### ISSUE TITLE
Behat tests failing on CircleCI

### ISSUE THREAD

**Issue by cjyabraham** [pantheon-systems/example-wordpress-composer#78]
My behat tests work locally but fail on CircleCI.  Here is [the gist](https://gist.github.com/cjyabraham/82948c502d1b7c155a012d427c944893).  I can visually inspect the dev site part way through the tests to see that the blogname etc are being changed correctly.   It's just that behat can't see that.

Any ideas?  One hint: I had to setup the whole infrastructure by hand, not using the build tools command, so I may have missed something...

**Comment by stevector** [comment]
Hi @cjyabraham thanks for the report. I see Behat is saying

```
The text "Awesome WordHat Test Site" was not found in the text of the element matching css ".site-title > a".
```

What text was found in `.site-title a`? Is your repo/site public?

**Comment by cjyabraham** [comment]
Thanks for the response.  `.site-title a` does contain "Awesome WordHat Test Site" at the point it is checked.  
![Here's a screenshot](https://user-images.githubusercontent.com/463160/52987283-0c892d00-342d-11e9-9896-5db69196f1a3.png)

You'll see the screenshot is captured from an incognito browser because I wanted to make sure that the cache wasn't getting in the way.  It's strange because the tests run fine in my local instance.  Any ideas?  [Here is the site's dev instance](http://dev-lfeventsci.pantheonsite.io/).

**Comment by ataylorme** [comment]
> You'll see the screenshot is captured from an incognito browser because I wanted to make sure that the cache wasn't getting in the way.

Perhaps the cache _is_ getting in the way when Behat is testing. Have you tried adding a cache clear step in the Behat tests (after the settings change but before verification on the front-end)?

**Comment by cjyabraham** [comment]
I have added steps to clear the cache prior to checking the updated text on the home page but I get the [same breaking test results](https://gist.github.com/cjyabraham/9175ede2ab5c28fa88e64eb9ab8515fd).

I then set the tests to check that the text is staying at it's current settings "lfeventsci123" and "Just another WordPress site123" and [confirmed that it is](https://gist.github.com/cjyabraham/61370acdc213b1aad74ac012df1835e4).  So something other than the Pantheon cache must be cacheing the original page.  Hmm...

**Comment by ataylorme** [comment]
@cjyabraham I think the source of the Varnish cache not being cleared is that [the WordHat cache clear runs `wp cache flush`](https://github.com/paulgibbs/behat-wordpress-extension/blob/master/src/Driver/Element/Wpcli/CacheElement.php#L20) which [clears the object cache](https://developer.wordpress.org/cli/commands/cache/flush/). So adding `When the cache is cleared` to the Behat tests won't actually clear the Varnish cache.

Perhaps a custom feature to clear Pantheon cache is needed.

**Comment by cjyabraham** [comment]
@ataylorme I'm not sure I understand.  In [my tests](https://gist.github.com/cjyabraham/9175ede2ab5c28fa88e64eb9ab8515fd) I go to the Pantheon settings to clear the cache.  Is this not what I want to do?

**Comment by ataylorme** [comment]
@cjyabraham ah, I didn't realize you were clearing the Pantheon cache in your tests.

I've experienced reliability issues with WordHat logging into WordPress. It has to do with [Mink not correctly filling in fields when a button click comes next](https://github.com/Behat/MinkExtension/issues/286).

I've opened [this PR](https://github.com/paulgibbs/behat-wordpress-extension/pull/230) to help improve the reliability of authenticating by filling in value with JS.

Anyway, I saw similar failures with cached items. I'm [working on a PR for `example-wordpress-composer`](https://github.com/pantheon-systems/example-wordpress-composer/pull/79) that uses the my Behat fork with the login changes.

It also adds a [custom context with a `clearPantheonCache` method](https://github.com/pantheon-systems/example-wordpress-composer/blob/custom-login/tests/behat/helper_classes/Contexts/PantheonContext.php#L204:L296).

You can see a [test very similar to yours](https://github.com/pantheon-systems/example-wordpress-composer/blob/custom-login/tests/behat/features/blogname.feature) using the new `clearPantheonCache` method and [it has been passing reliably](https://circleci.com/gh/pantheon-systems/example-wordpress-composer/1148).

I'm hoping my upstream changes to WordHat will get merged, then I can merge the changes to `example-wordpress-composer` as well.

We are working on some refactoring of build tools and GitLab support, hoping to have a stable release by April for Drupalcon Seattle.

**Comment by cjyabraham** [comment]
Hi @ataylorme .  Thanks for the info.  I took [your test](https://github.com/pantheon-systems/example-wordpress-composer/blob/custom-login/tests/behat/features/blogname.feature) and adapted it to work for me and now my tests are passing.  I can't say I fully understand why my old test didn't pass, but I'm happy to move on for now.  Thanks for your help and I'll be keeping an eye on example-wordpress-composer for future updates.
