### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/example-wordpress-composer#8]
@greg-1-anderson and @ataylorme. This repo currently requires PHP 7.1 because of packages used by WordHat. Pantheon's highest version currently is 7.0. I know it isn't strictly necessary that these line up because WordHat is getting run outside of Pantheon. But it is a likely source of confusion. Any thoughts on how to handle this mismatch?

**Comment by ataylorme** [comment]
@stevector I don't think it's a big issue since the version is higher on CircleCI. If there was a large discrepancy between version I would be more concerned about PHP Unit tests than Behat tests as those are run entirely on CircleCI where, like you said, the Behat tests are run on Pantheon.

**Comment by stevector** [comment]
A specific problem developers could encounter is the inability to run many Composer commands on Pantheon:

```
terminus composer  build-tools-343.dev  --   install
 [warning] This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ocramius/proxy-manager 2.1.1 requires php ^7.1.0 -> your PHP version (7.0.18) does not satisfy that requirement.
    - ocramius/proxy-manager 2.1.1 requires php ^7.1.0 -> your PHP version (7.0.18) does not satisfy that requirement.
    - Installation request for ocramius/proxy-manager 2.1.1 -> satisfiable by ocramius/proxy-manager[2.1.1].
```

This is not a hard blocker since we're encouraging most/all Composer commands to be run locally before pushing up to GitHub. That being said, I've still had reason to run Composer commands on Pantheon for sites using this GitHub/Circle setup.

Let's update this repo as soon as Pantheon announces 7.1 as being available.

**Comment by ataylorme** [comment]
> A specific problem developers could encounter is the inability to run many Composer commands on Pantheon

Good call, I hadn't thought about that use case, running `composer update` on Pantheon and committing back to GitHub with the Quicksilver pushback.

**Comment by ataylorme** [comment]
`example-wordpress-composer` uses PHP `7.3`
