### ISSUE TITLE
EDGE URLs no longer working

### ISSUE THREAD

**Issue by cjyabraham** [pantheon-systems/example-wordpress-composer#97]
My Lando local instance used to work fine on all urls but for no reason it stopped working on the EDGE urls.  I see this screenshot with the urls in red.
![Screen Shot 2019-05-01 at 12 18 42 PM](https://user-images.githubusercontent.com/463160/57006474-4afc4e80-6c0b-11e9-8ea2-23e4ed7f47d2.png)

When I try to access them in my browser I get a "Bad Gateway" message.

I tried re-installing the whole instance from scratch and got the same result.  Funnily, when I try to point at a different Pantheon instance, like `lfasiallcci`, all urls work fine.

Any idea why these urls suddenly stopped working for my `lfeventsci` Pantheon instance and how to get them to work again?

**Comment by ataylorme** [comment]
@cjyabraham I don't think this is the right place for that question. This example repo doesn't use/have Lando.

Try the troubleshooting section of [the Lando docs](https://docs.devwithlando.io/). You can also [open an issue on Lando's GitHub instance](https://github.com/lando/lando/issues).

That being said, `lando rebuild` or deleting you Docker cache might help.
